apiVersion: v1
kind: Service
metadata:
  name: svc-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: balance
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31112
      protocol: "TCP" 
      
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-03
  labels:
    app: balance
spec:
    containers:
      - name: con-03
        image: nginx:latest
        ports:
          - containerPort: 80