apiVersion: v1
kind: Service
metadata:
  name: my-svc-nodeport-01
spec:
  type: NodePort
  selector:
    app: nodeport
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31111
      protocol: "TCP"

---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-04
  labels:
    app:  nodeport
spec:
  containers:
    - name: my-con-04
      image: nginx:latest
      ports:
        - containerPort: 80
